name: Build and Deploy API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-1caaf581-2331-41dd-8b0
      
      - name: Configure Docker
        run: gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev
      
      - name: Build and Push
        run: |
          docker build -t northamerica-northeast1-docker.pkg.dev/project-1caaf581-2331-41dd-8b0/ai-oracle-repo/oracle-rag-api:${{ github.sha }} .
          docker push northamerica-northeast1-docker.pkg.dev/project-1caaf581-2331-41dd-8b0/ai-oracle-repo/oracle-rag-api:${{ github.sha }}
